#!/usr/bin/bash
alias_etc=.zalias_etc
configurations=(.virc $alias_etc .gitconfig .gitignore-files)
commands=(eslint_init git_init)
command_dir=/usr/bin

bold=$(tput bold)
normal=$(tput sgr0)

case "$1" in
    --reverse)
        reverse=true
        # Reading files to current directory
        ;;
    *)
        if [ -n "$1" ]; then
            echo "Unknown option"
            exit 1
        fi
        # Distributing files
        ;;
esac

source_alias="source \$HOME/$alias_etc"
if ! grep -q "$source_alias" ~/.zshrc ; then
    echo  "${bold}Adding $source_alias to ~/.zshrc${normal}"
    echo $source_alias >> ~/.zshrc
fi

echo "${bold}Copying personal configuration files${normal}"
for f in "${configurations[@]}"
do
    if [ "$reverse" = true ]; then
        cp -rvT "$HOME/$f" ./"$f"
    else
        cp -rviT "$f" "$HOME/$f"
    fi
done

echo "${bold}Copying personal commands${normal}"
for f in "${commands[@]}"
do
    if [ "$reverse" = true ]; then
        cp -v "$command_dir/$f" "$f"
    else
        cp -v "$f" "$command_dir/$f"
    fi
done
